---
title: "LTPP Website"
output:
  html_document:
    toc: true
    toc_float: true
---

# Introduction

Hello, this a Summary of the NZ LTPP programmes data to 2021!  
  
The aim of the site is to display the data from the NZ LTPP programme graphically and show case the freeware statistical software used to do this.
  
You will see the code used to extract the data from the LTPP database, tidy the data, graphically display the data and then you will see the graphics.  
  
The site is deliberately doing this as part of "Data Science" approach to make analysis accessible and reproducible.
    
All the code is available for download at Github and a copy of the database is available from the NZTA. 
  
The site contains only 8 pages but they contain a lot of detail as the short descriptions below will explain.
   
(@) The Home page - i.e. this page, contains the purpose and the structure of the site  
(@) The About page - explains how to make a website like this  
(@) The LTPP Summary page - contains a giant graphic showing all the data for each of the big 3 (Rutting, Roughness, Texture)  
(@) The Rutting page - contains graphics showing all the sites together, the sites split to SH and Council roads and finally each individual site
(@) The Roughness page - contains graphics showing all the sites together, the sites split to SH and Council roads and finally each individual site
(@) The Texture page - contains graphics showing all the sites together, the sites split to SH and Council roads and finally each individual site
(@) The Ratings page - contains a giant graphic showing all the data for all sites for each visual rating type   
(@) The Table page - provides all the table type data - its ugly as the the field names in the database are long   

# Site Structure

The tabs at the top of the page will take you to other pages containing the data.  

# Menu  
  
The menu to the left will jump to titles locations on the page.  

## 2nd Level Menus
  
There are often sub-menus hidden under a main menu that will take you to 2nd level titles on the page.  Click on Menu on the left to see this.


# Software used

It is a beta site hosted on Github and written with R and R Studio.  
  
R and Rstudio are very well documented online.  
  
A detailed discription on how to create a site like this is on the "About" page.  



